package cn.edu.uestc.meet_on_the_road_of_uestc.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.eneities.StuInfo;
import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.eneities.traceInfo;
import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.eneities.HelpInfo;

import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.StuInfoDao;
import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.traceInfoDao;
import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.HelpInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stuInfoDaoConfig;
    private final DaoConfig traceInfoDaoConfig;
    private final DaoConfig helpInfoDaoConfig;

    private final StuInfoDao stuInfoDao;
    private final traceInfoDao traceInfoDao;
    private final HelpInfoDao helpInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stuInfoDaoConfig = daoConfigMap.get(StuInfoDao.class).clone();
        stuInfoDaoConfig.initIdentityScope(type);

        traceInfoDaoConfig = daoConfigMap.get(traceInfoDao.class).clone();
        traceInfoDaoConfig.initIdentityScope(type);

        helpInfoDaoConfig = daoConfigMap.get(HelpInfoDao.class).clone();
        helpInfoDaoConfig.initIdentityScope(type);

        stuInfoDao = new StuInfoDao(stuInfoDaoConfig, this);
        traceInfoDao = new traceInfoDao(traceInfoDaoConfig, this);
        helpInfoDao = new HelpInfoDao(helpInfoDaoConfig, this);

        registerDao(StuInfo.class, stuInfoDao);
        registerDao(traceInfo.class, traceInfoDao);
        registerDao(HelpInfo.class, helpInfoDao);
    }
    
    public void clear() {
        stuInfoDaoConfig.clearIdentityScope();
        traceInfoDaoConfig.clearIdentityScope();
        helpInfoDaoConfig.clearIdentityScope();
    }

    public StuInfoDao getStuInfoDao() {
        return stuInfoDao;
    }

    public traceInfoDao getTraceInfoDao() {
        return traceInfoDao;
    }

    public HelpInfoDao getHelpInfoDao() {
        return helpInfoDao;
    }

}
