package cn.edu.uestc.meet_on_the_road_of_uestc.greenDao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import cn.edu.uestc.meet_on_the_road_of_uestc.greenDao.eneities.traceInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRACE_INFO".
*/
public class traceInfoDao extends AbstractDao<traceInfo, String> {

    public static final String TABLENAME = "TRACE_INFO";

    /**
     * Properties of entity traceInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Date = new Property(0, String.class, "date", true, "DATE");
        public final static Property StuID = new Property(1, String.class, "stuID", false, "STU_ID");
        public final static Property Latitude = new Property(2, String.class, "latitude", false, "LATITUDE");
        public final static Property Lontitude = new Property(3, String.class, "lontitude", false, "LONTITUDE");
        public final static Property Speed = new Property(4, double.class, "speed", false, "SPEED");
        public final static Property AvgSpeed = new Property(5, double.class, "avgSpeed", false, "AVG_SPEED");
        public final static Property StartTime = new Property(6, Long.class, "startTime", false, "START_TIME");
        public final static Property StopTime = new Property(7, Long.class, "stopTime", false, "STOP_TIME");
        public final static Property Time = new Property(8, Long.class, "time", false, "TIME");
    }

    private Query<traceInfo> stuInfo_TraceInfoListQuery;

    public traceInfoDao(DaoConfig config) {
        super(config);
    }
    
    public traceInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRACE_INFO\" (" + //
                "\"DATE\" TEXT PRIMARY KEY NOT NULL ," + // 0: date
                "\"STU_ID\" TEXT," + // 1: stuID
                "\"LATITUDE\" TEXT," + // 2: latitude
                "\"LONTITUDE\" TEXT," + // 3: lontitude
                "\"SPEED\" REAL NOT NULL ," + // 4: speed
                "\"AVG_SPEED\" REAL NOT NULL ," + // 5: avgSpeed
                "\"START_TIME\" INTEGER," + // 6: startTime
                "\"STOP_TIME\" INTEGER," + // 7: stopTime
                "\"TIME\" INTEGER);"); // 8: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRACE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, traceInfo entity) {
        stmt.clearBindings();
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(1, date);
        }
 
        String stuID = entity.getStuID();
        if (stuID != null) {
            stmt.bindString(2, stuID);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(3, latitude);
        }
 
        String lontitude = entity.getLontitude();
        if (lontitude != null) {
            stmt.bindString(4, lontitude);
        }
        stmt.bindDouble(5, entity.getSpeed());
        stmt.bindDouble(6, entity.getAvgSpeed());
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(7, startTime);
        }
 
        Long stopTime = entity.getStopTime();
        if (stopTime != null) {
            stmt.bindLong(8, stopTime);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(9, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, traceInfo entity) {
        stmt.clearBindings();
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(1, date);
        }
 
        String stuID = entity.getStuID();
        if (stuID != null) {
            stmt.bindString(2, stuID);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(3, latitude);
        }
 
        String lontitude = entity.getLontitude();
        if (lontitude != null) {
            stmt.bindString(4, lontitude);
        }
        stmt.bindDouble(5, entity.getSpeed());
        stmt.bindDouble(6, entity.getAvgSpeed());
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(7, startTime);
        }
 
        Long stopTime = entity.getStopTime();
        if (stopTime != null) {
            stmt.bindLong(8, stopTime);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(9, time);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public traceInfo readEntity(Cursor cursor, int offset) {
        traceInfo entity = new traceInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // date
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // stuID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // latitude
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // lontitude
            cursor.getDouble(offset + 4), // speed
            cursor.getDouble(offset + 5), // avgSpeed
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // startTime
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // stopTime
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, traceInfo entity, int offset) {
        entity.setDate(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStuID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLatitude(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLontitude(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSpeed(cursor.getDouble(offset + 4));
        entity.setAvgSpeed(cursor.getDouble(offset + 5));
        entity.setStartTime(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setStopTime(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setTime(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(traceInfo entity, long rowId) {
        return entity.getDate();
    }
    
    @Override
    public String getKey(traceInfo entity) {
        if(entity != null) {
            return entity.getDate();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(traceInfo entity) {
        return entity.getDate() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "traceInfoList" to-many relationship of StuInfo. */
    public List<traceInfo> _queryStuInfo_TraceInfoList(String stuID) {
        synchronized (this) {
            if (stuInfo_TraceInfoListQuery == null) {
                QueryBuilder<traceInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.StuID.eq(null));
                stuInfo_TraceInfoListQuery = queryBuilder.build();
            }
        }
        Query<traceInfo> query = stuInfo_TraceInfoListQuery.forCurrentThread();
        query.setParameter(0, stuID);
        return query.list();
    }

}
