language: android
sudo: true
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-26  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-N
  - extra
licenses:
- android-sdk-license-.+
- .+
before_install:
- openssl aes-256-cbc -K $encrypted_8b4a791eae2c_key -iv $encrypted_8b4a791eae2c_iv
  -in MEET_ON_THE_ROAD.jks.enc -out MEET_ON_THE_ROAD.jks -d
- mkdir "%ANDROID_HOME%\licenses"
- echo |set /p="8933bad161af4178b1185d1a37fbf41ea5269c55" > "%ANDROID_HOME%\licenses\android-sdk-license"
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo y | android update sdk --no-ui --all --filter build-tools-28.0.3,android-28
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
   secure: M6hwUKq70tCgFARqavlkqxLfyD1u+sPlBxb9rwrjKHuWjPKefGzBJ0wm3iqs8o83asn8iYFavqCdXmgwnhmvarmflyGqx9hIm3pSm26tOUD+Xb28uy6QHMFECg8jxZx1NeU2Ns3ltRUWOg6ayUvIGOLCp/iFZOXoewnwF0kxoVqalXiM2Dfnhh4kQIOoG6QWbqQcn7alVcubmUJgMZM//T230gZ8HEY++YwL8J0jueNmbbPJzEhsaY7H3nFE2nxW8lYR7XD9RK8CwIwgCoMRPX90XvH9fcP+k4+CVqv+ZXl811gIitq3wtTHvbM8ZIAdKuxP5TvlE57remqgsR0XLe2FR3V5wNYg/AB3ArKO7euPawSpcKhnVth+Hasku+WceWXg14ZYnUUEisSwW054X2C8kZcm2pB6Nj2ELlHt8SAh+2Lia38gCLFK1ecL9PLIMwrknzcSy8gEul65rKiC0A26CfCbYx+5U/XWCXNxhfcQi2+VE6trqrl/UCuk4qzs212KqlBb71XGVkxSruwKSEhASP2HUj31+un/Zwmy7nzAsv9GBfmWrnJgRk+KnVlSWkAOgAYNXPKPInmfIA9e+/vLIwswGtGLoOj88M6Is7T3yhvPZcXGWsHihKO0JpfLRjJwHsFQ8vH/HYiQl38lgJ0Ws/oRcTxIRLYe3rajTgk=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: Meet-on-the-road-of-UESTC/Meet-on-the-road-of-UESTC-Android
