language: android
sudo: false
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-26  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-N
  - extra
licenses:
- android-sdk-license-.+
- .+
before_install:
- openssl aes-256-cbc -K $encrypted_6b42a8524af0_key -iv $encrypted_6b42a8524af0_iv
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
script:
- ./gradlew assembleRelease