language: android
sudo: true
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-26  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-N
  - extra
licenses:
- android-sdk-license-.+
- .+
before_install:
- openssl aes-256-cbc -K $encrypted_8b4a791eae2c_key -iv $encrypted_8b4a791eae2c_iv
  -in MEET_ON_THE_ROAD.jks.enc -out MEET_ON_THE_ROAD.jks -d
- mkdir "%ANDROID_HOME%\licenses"
- echo |set /p="8933bad161af4178b1185d1a37fbf41ea5269c55" > "%ANDROID_HOME%\licenses\android-sdk-license"
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo y | android update sdk --no-ui --all --filter build-tools-28.0.3,android-28
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: lrZD7HQiX7Y3BRZROXpQePrquXNt7C1FrOEHeawxs8I7dOJ1LHedzKRHwxGlSytfw7MPxucvxYKrWCP9WV/x8kgdZM7t3himT7VmFxMZgc6SvAzniAdSVVAS/uJxIdbgB/aJXR3h9cgoRH2QzEO8ajIiAKj9THY8MIPpfzPSBRUlMStxmhiULqeosZmrrPM5WSj39nGqrdSrQNufsk3nv4x50T2DVLsmqqDQwFLp78nK7MnZxYNiwLz87E1STLyxfnRKS1yqv7qjowMgxFBsrAaYydhAnKvGnO2W+cvofHBaNLLn37bhQEdh7WHOLBtkFwNdCbt5bUi7V/pmqpIeEI86BWWRXzrXT8WVMauxTuMswgiTsyA8RjZ4A8fVGKab/kCExK50vzUGYet2yAmuXf5mdjQ5GP2v+Jg/smYQqDisqrqAAeStoPUrD0PfQEamNuETH6++tMppDaH2ViDNp8EyARgR4VJLnNKPqek6vGPvZolmiKohekuCGtaP1eRPFnLbINn2hea0C1ldxLyfHHhQGck4RV0DjAF4CNRkp4cSTXZpHzcK64txzxYANkUhC18IFL0NFgW8tbGgFiHk4+CkBREMV+Y4eUmCxlUeV9cDEs4m27cc9Ud7+kAenYvVfxqT00fypBfaBPl0OniFYQA/gd3jcmG6xO5UqxHCUDQ=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: Meet-on-the-road-of-UESTC/Meet-on-the-road-of-UESTC-Android
