language: android
sudo: true
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-26  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-N
  - extra
licenses:
- android-sdk-license-.+
- .+
- android-sdk-preview-license-.+
- 'google-gdk-license-.+'
before_install:
- mkdir "%ANDROID_HOME%\licenses"
- echo |set /p="8933bad161af4178b1185d1a37fbf41ea5269c55" > "%ANDROID_HOME%\licenses\android-sdk-license"
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
script:
- ./gradlew assembleRelease